# Generated by Django 5.0.3 on 2024-03-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Yangilik', 'verbose_name_plural': 'Yangiliklar'},
        ),
        migrations.AlterModelOptions(
            name='types',
            options={'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.AddField(
            model_name='news',
            name='body',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
