# Generated by Django 5.0.3 on 2024-03-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_options_alter_types_options_news_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('body', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'New', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='types',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
