# Generated by Django 5.0.4 on 2024-04-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_commentmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='views',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
