# Generated by Django 5.0.4 on 2024-04-15 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_news_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='views',
        ),
    ]
