# Generated by Django 5.0.4 on 2024-04-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profilemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
