# Generated by Django 5.0.4 on 2024-04-15 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profilemodel_age_alter_profilemodel_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilemodel',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='userauthdatamodels',
            options={'verbose_name': 'Users password list', 'verbose_name_plural': 'Users password lists'},
        ),
    ]
