# Generated by Django 5.0.4 on 2024-05-16 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profilemodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='age',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='bio',
        ),
    ]
